name: JavaScript

on:
  push:
    branches:
    - "5.2"
    - "5.3"
    - "5.4"
    - master
  pull_request:

jobs:
  syntax:
    name: "Check Syntax"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - run: echo "::add-matcher::.github/javascript-syntax.json"
    - name: Remove files to be ignored
      run: |
        true
    - run: |
        ! find . -type f -name '*.js' -exec node -c '{}' \; 2>&1 \
          |awk 'BEGIN {m=0} /(.js):[0-9]+$/ {m=1; printf "%s - ",$0} m==1 && /^SyntaxError/ { m=0; print }' \
          |sed "s@$(pwd)@.@" \
          |grep '^'
